# Generated by Django 4.0.3 on 2022-03-28 21:57

import core.utils.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestimentFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=150)),
                ('administrator', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18)),
                ('benchmark', models.CharField(max_length=25)),
                ('fund_type', models.CharField(choices=[('Fund Type 1', 'FUND_TYPE_1'), ('Fund Type 2', 'FUND_TYPE_2'), ('Fund Type 3', 'FUND_TYPE_3')], default=core.utils.enums.FundType['FUND_TYPE_1'], max_length=25)),
                ('fund_class', models.CharField(choices=[('Fund Class 1', 'FUND_CLASS_1'), ('Fund Class 2', 'FUND_CLASS_2'), ('Fund Class 3', 'FUND_CLASS_3')], default=core.utils.enums.FundClass['FUND_CLASS_1'], max_length=25)),
                ('fund_subclass', models.CharField(choices=[('Fund Subclass 1', 'FUND_SUBCLASS_1'), ('Fund Subclass 2', 'FUND_SUBCLASS_2'), ('Fund Subclass 3', 'FUND_SUBCLASS_3')], default=core.utils.enums.FundSubclass['FUND_SUBCLASS_1'], max_length=25)),
            ],
            options={
                'verbose_name': 'Investiment Fund',
                'verbose_name_plural': ' Investiment Funds',
                'db_table': 'investiment_fund',
            },
        ),
    ]
