# Generated by Django 4.0.3 on 2022-03-28 22:56

import core.utils.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_investimentfund_fund_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimentfund',
            name='administrator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investimentfund',
            name='benchmark',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='investimentfund',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='investimentfund',
            name='fund_class',
            field=models.CharField(blank=True, choices=[('Fund Class 1', 'FUND_CLASS_1'), ('Fund Class 2', 'FUND_CLASS_2'), ('Fund Class 3', 'FUND_CLASS_3')], default=core.utils.enums.FundClass['FUND_CLASS_1'], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='investimentfund',
            name='fund_subclass',
            field=models.CharField(blank=True, choices=[('Fund Subclass 1', 'FUND_SUBCLASS_1'), ('Fund Subclass 2', 'FUND_SUBCLASS_2'), ('Fund Subclass 3', 'FUND_SUBCLASS_3')], default=core.utils.enums.FundSubclass['FUND_SUBCLASS_1'], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='investimentfund',
            name='fund_type',
            field=models.CharField(blank=True, choices=[('Fund Type 1', 'FUND_TYPE_1'), ('Fund Type 2', 'FUND_TYPE_2'), ('Fund Type 3', 'FUND_TYPE_3')], default=core.utils.enums.FundType['FUND_TYPE_1'], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='investimentfund',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investimentfund',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
